api:
  bind_address: '0.0.0.0'
  bind_port: 9000
  max_size: 33554432
  default_ttl: 604800
  frontend: 'frontend.html'
  base_url: 'https://paste.nurd.space'

redis:
  host: 'redis'
  port: 6379

logging:
  logger: 'default'
  config: 'logging.yml'
